name: "Build iOS app"

on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          # Updated project structure based on image.png
          xcodebuild archive -workspace Gemini.xcworkspace -scheme 'Gemini' -archivePath Gemini.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv Gemini.xcarchive/Products/Applications/Gemini.app Payload/Gemini.app

          # Set display name to Gemini Web
          DISPLAY_NAME="Gemini Web"
          if [ "$DISPLAY_NAME" != "Gemini" ] && [ -n "$DISPLAY_NAME" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $DISPLAY_NAME" "Payload/Gemini.app/Info.plist"
            /usr/libexec/PlistBuddy -c "Set :CFBundleName $DISPLAY_NAME" "Payload/Gemini.app/Info.plist"
          fi

          zip -r "Gemini Web.ipa" "Payload"

          mv "Gemini Web.ipa" "${{ runner.temp }}/Gemini Web.ipa"

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: GeminiWeb
          path: ${{ runner.temp }}/Gemini Web.ipa
          retention-days: 3
