name: "Build iOS app"

on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          xcodebuild archive -project CAPyTCHA.xcodeproj -scheme 'CAPyTCHA' -archivePath CAPyTCHA.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv CAPyTCHA.xcarchive/Products/Applications/CAPyTCHA.app Payload/CAPyTCHA.app

          # Set display name to Gemini Web
          DISPLAY_NAME="Gemini Web"
          if [ "$DISPLAY_NAME" != "CAPyTCHA" ] && [ -n "$DISPLAY_NAME" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $DISPLAY_NAME" "Payload/CAPyTCHA.app/Info.plist"
            /usr/libexec/PlistBuddy -c "Set :CFBundleName $DISPLAY_NAME" "Payload/CAPyTCHA.app/Info.plist"
          fi

          zip -r "CAPyTCHA.ipa" "Payload"

          mv CAPyTCHA.ipa ${{ runner.temp }}/CAPyTCHA.ipa

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: CAPyTCHA
          path: ${{ runner.temp }}/CAPyTCHA.ipa
          retention-days: 3
